"""Add role column to users

Revision ID: f5f8f2fe3454
Revises: 
Create Date: 2024-08-10 15:16:21.035244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5f8f2fe3454'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacantes')
    op.drop_table('empresas')
    op.drop_table('aspirantes')
    op.drop_table('postulaciones')
    op.add_column('users', sa.Column('role', sa.Enum('aspirante', 'empresa', name='rolesenum'), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role')
    op.create_table('postulaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('aspirante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('vacante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_postulacion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['aspirante_id'], ['aspirantes.id'], name='postulaciones_ibfk_1'),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], name='postulaciones_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_general_ci',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('aspirantes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cv_url', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_general_ci',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('empresas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('ubicacion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_general_ci',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('vacantes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('subtitulo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('modo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('salario', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='vacantes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_general_ci',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
